# Generated by Django 4.2 on 2023-04-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
